import { Cormorant_Garamond  } from 'next/font/google';

import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.scss';

const cormorant = Cormorant_Garamond({
  variable: '--font-geist-sans',
  subsets: ['latin', 'cyrillic', 'cyrillic-ext'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${cormorant.variable}  antialiased`}>{children}</body>
    </html>
  );
}
