import {
  Wifi,
  Tv,
  ShieldCheck,
  Wind,
  Wine,
  Coffee,
  Bath,
  Waves,
  Mountain,
  Trees,
  Building2,
  Sofa,
  Phone,
  Sparkles,
  Shrub,
} from 'lucide-react';

import type { LucideIcon } from 'lucide-react';


export enum AmenityKey {
  WIFI = 'WIFI',
  TV = 'TV',
  SAFE = 'SAFE',
  BALCONY = 'BALCONY',
  AIR_CONDITIONER = 'AIR_CONDITIONER',
  MINI_BAR = 'MINI_BAR',
  KETTLE = 'KETTLE',
  COFFEE_MACHINE = 'COFFEE_MACHINE',
  HAIR_DRYER = 'HAIR_DRYER',
  IRON = 'IRON',
  IRON_BOARD = 'IRON_BOARD',
  BATHROBE = 'BATHROBE',
  SLIPPERS = 'SLIPPERS',
  TOILETRIES = 'TOILETRIES',
  TOWELS = 'TOWELS',
  DESK = 'DESK',
  SOFA = 'SOFA',
  WARDROBE = 'WARDROBE',
  TELEPHONE = 'TELEPHONE',
  ROOM_SERVICE = 'ROOM_SERVICE',
  DAILY_CLEANING = 'DAILY_CLEANING',
  SEA_VIEW = 'SEA_VIEW',
  GARDEN_VIEW = 'GARDEN_VIEW',
  POOL_VIEW = 'POOL_VIEW',
  MOUNTAIN_VIEW = 'MOUNTAIN_VIEW',
  TERRACE = 'TERRACE',
  PRIVATE_POOL = 'PRIVATE_POOL',
  JACUZZI = 'JACUZZI',
  HEATING = 'HEATING',
  SOUNDPROOFING = 'SOUNDPROOFING',
}

export const AMENITY_ICONS: Record<AmenityKey, LucideIcon> = {
  [AmenityKey.WIFI]: Wifi,
  [AmenityKey.TV]: Tv,
  [AmenityKey.SAFE]: ShieldCheck,
  [AmenityKey.BALCONY]: Shrub,
  [AmenityKey.AIR_CONDITIONER]: Wind,
  [AmenityKey.MINI_BAR]: Wine,
  [AmenityKey.KETTLE]: Coffee,
  [AmenityKey.COFFEE_MACHINE]: Coffee,
  [AmenityKey.HAIR_DRYER]: Wind,
  [AmenityKey.IRON]: Sparkles,
  [AmenityKey.IRON_BOARD]: Sparkles,
  [AmenityKey.BATHROBE]: Bath,
  [AmenityKey.SLIPPERS]: Sparkles,
  [AmenityKey.TOILETRIES]: Sparkles,
  [AmenityKey.TOWELS]: Bath,
  [AmenityKey.DESK]: Building2,
  [AmenityKey.SOFA]: Sofa,
  [AmenityKey.WARDROBE]: Building2,
  [AmenityKey.TELEPHONE]: Phone,
  [AmenityKey.ROOM_SERVICE]: Sparkles,
  [AmenityKey.DAILY_CLEANING]: Sparkles,
  [AmenityKey.SEA_VIEW]: Waves,
  [AmenityKey.GARDEN_VIEW]: Trees,
  [AmenityKey.POOL_VIEW]: Waves,
  [AmenityKey.MOUNTAIN_VIEW]: Mountain,
  [AmenityKey.TERRACE]: Building2,
  [AmenityKey.PRIVATE_POOL]: Waves,
  [AmenityKey.JACUZZI]: Bath,
  [AmenityKey.HEATING]: Wind,
  [AmenityKey.SOUNDPROOFING]: Sparkles,
};

export const AMENITY_LABEL_RU: Record<string, string> = {
  WIFI: "Wi-Fi",
  TV: "Телевизор",
  SAFE: "Сейф",
  BALCONY: "Балкон",
  AIR_CONDITIONER: "Кондиционер",
  MINI_BAR: "Мини-бар",
  KETTLE: "Чайник",
  COFFEE_MACHINE: "Кофемашина",
  HAIR_DRYER: "Фен",
  IRON: "Утюг",
  IRON_BOARD: "Гладильная доска",
  BATHROBE: "Халат",
  SLIPPERS: "Тапочки",
  TOILETRIES: "Косметика",
  TOWELS: "Полотенца",
  DESK: "Рабочий стол",
  SOFA: "Диван",
  WARDROBE: "Шкаф",
  TELEPHONE: "Телефон",
  ROOM_SERVICE: "Обслуживание номеров",
  DAILY_CLEANING: "Ежедневная уборка",
  SEA_VIEW: "Вид на море",
  GARDEN_VIEW: "Вид на сад",
  POOL_VIEW: "Вид на бассейн",
  MOUNTAIN_VIEW: "Вид на горы",
  TERRACE: "Терраса",
  PRIVATE_POOL: "Частный бассейн",
  JACUZZI: "Джакузи",
  HEATING: "Отопление",
  SOUNDPROOFING: "Шумоизоляция",
};