export const sitemap: Record<string, string> = {
  setting: 'Настройки',
  profile: 'Профиль',
  fqa: 'FQA',
  about: 'О нас',
  support: 'Поддержка',
  message: 'Чат',
  hotels: 'Отели',
  booking: 'Бронирования',
  rooms: 'Комнаты',
  admin: 'Админ',
  new: 'Добавить',
  delete: 'Удалить',
  edit: 'Обновить',
};